//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Localizations.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User blocked.
        /// </summary>
        internal static string BlockedUserException {
            get {
                return ResourceManager.GetString("BlockedUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        internal static string CategoryNotFoundException {
            get {
                return ResourceManager.GetString("CategoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent category can&apos;t be child itself.
        /// </summary>
        internal static string CategoryParentException {
            get {
                return ResourceManager.GetString("CategoryParentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category tier over max category tier.
        /// </summary>
        internal static string CategoryTierException {
            get {
                return ResourceManager.GetString("CategoryTierException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country not found.
        /// </summary>
        internal static string CountryNotFoundException {
            get {
                return ResourceManager.GetString("CountryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery type not found.
        /// </summary>
        internal static string DeliveryTypeNotFoundException {
            get {
                return ResourceManager.GetString("DeliveryTypeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already in user.
        /// </summary>
        internal static string EmailInUseException {
            get {
                return ResourceManager.GetString("EmailInUseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not confirmed.
        /// </summary>
        internal static string EmailNotConfirmedException {
            get {
                return ResourceManager.GetString("EmailNotConfirmedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not found.
        /// </summary>
        internal static string GenericEntityNotFoundExceptiGenericEntityNotFoundException {
            get {
                return ResourceManager.GetString("GenericEntityNotFoundExceptiGenericEntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect jwt-token.
        /// </summary>
        internal static string IncorrectJWTException {
            get {
                return ResourceManager.GetString("IncorrectJWTException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method not found.
        /// </summary>
        internal static string PaymentMethodNotFoundException {
            get {
                return ResourceManager.GetString("PaymentMethodNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        internal static string ProductNotFoundException {
            get {
                return ResourceManager.GetString("ProductNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need required property.
        /// </summary>
        internal static string RequiredImportPropertyException {
            get {
                return ResourceManager.GetString("RequiredImportPropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review not found.
        /// </summary>
        internal static string ReviewNotFoundException {
            get {
                return ResourceManager.GetString("ReviewNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop not found.
        /// </summary>
        internal static string ShopNotFoundException {
            get {
                return ResourceManager.GetString("ShopNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not found.
        /// </summary>
        internal static string TypeNotFoundException {
            get {
                return ResourceManager.GetString("TypeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email address.
        /// </summary>
        internal static string WrongEmailAddressException {
            get {
                return ResourceManager.GetString("WrongEmailAddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong file extentsion.
        /// </summary>
        internal static string WrongExtensionException {
            get {
                return ResourceManager.GetString("WrongExtensionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong INN.
        /// </summary>
        internal static string WrongINNException {
            get {
                return ResourceManager.GetString("WrongINNException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        internal static string WrongPasswordException {
            get {
                return ResourceManager.GetString("WrongPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong verification code.
        /// </summary>
        internal static string WrongVerificationCodeException {
            get {
                return ResourceManager.GetString("WrongVerificationCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file read error.
        /// </summary>
        internal static string XmlSerializationException {
            get {
                return ResourceManager.GetString("XmlSerializationException", resourceCulture);
            }
        }
    }
}
