//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationsWrapper_ruuu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationsWrapper_ruuu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Localizations.LocalizationsWrapper.ruuu", typeof(LocalizationsWrapper_ruuu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь заблокирован.
        /// </summary>
        public static string BlockedUserException {
            get {
                return ResourceManager.GetString("BlockedUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория не найдена.
        /// </summary>
        public static string CategoryNotFoundException {
            get {
                return ResourceManager.GetString("CategoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория не может иметь родительскую в потомках.
        /// </summary>
        public static string CategoryParentException {
            get {
                return ResourceManager.GetString("CategoryParentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный уровень категории: .
        /// </summary>
        public static string CategoryTierException {
            get {
                return ResourceManager.GetString("CategoryTierException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна не найдена.
        /// </summary>
        public static string CountryNotFoundException {
            get {
                return ResourceManager.GetString("CountryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип доставки не найден.
        /// </summary>
        public static string DeliveryTypeNotFoundException {
            get {
                return ResourceManager.GetString("DeliveryTypeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email уже используется.
        /// </summary>
        public static string EmailInUseException {
            get {
                return ResourceManager.GetString("EmailInUseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email не подтверждён.
        /// </summary>
        public static string EmailNotConfirmedException {
            get {
                return ResourceManager.GetString("EmailNotConfirmedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект не найден.
        /// </summary>
        public static string GenericEntityNotFoundExceptiGenericEntityNotFoundException {
            get {
                return ResourceManager.GetString("GenericEntityNotFoundExceptiGenericEntityNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный токен авторизации.
        /// </summary>
        public static string IncorrectJWTException {
            get {
                return ResourceManager.GetString("IncorrectJWTException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Метод оплаты не найден.
        /// </summary>
        public static string PaymentMethodNotFoundException {
            get {
                return ResourceManager.GetString("PaymentMethodNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт не найден.
        /// </summary>
        public static string ProductNotFoundException {
            get {
                return ResourceManager.GetString("ProductNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требуется необходимое поле для импорта:.
        /// </summary>
        public static string RequiredImportPropertyException {
            get {
                return ResourceManager.GetString("RequiredImportPropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзыв не найден.
        /// </summary>
        public static string ReviewNotFoundException {
            get {
                return ResourceManager.GetString("ReviewNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазин не найден.
        /// </summary>
        public static string ShopNotFoundException {
            get {
                return ResourceManager.GetString("ShopNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип магазина не найден.
        /// </summary>
        public static string TypeNotFoundException {
            get {
                return ResourceManager.GetString("TypeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        public static string UserNotFoundException {
            get {
                return ResourceManager.GetString("UserNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный Email адрес.
        /// </summary>
        public static string WrongEmailAddressException {
            get {
                return ResourceManager.GetString("WrongEmailAddressException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное расширение файла.
        /// </summary>
        public static string WrongExtensionException {
            get {
                return ResourceManager.GetString("WrongExtensionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный ИНН.
        /// </summary>
        public static string WrongINNException {
            get {
                return ResourceManager.GetString("WrongINNException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пароль.
        /// </summary>
        public static string WrongPasswordException {
            get {
                return ResourceManager.GetString("WrongPasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный код подтверждения.
        /// </summary>
        public static string WrongVerificationCodeException {
            get {
                return ResourceManager.GetString("WrongVerificationCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка чтения XML файла.
        /// </summary>
        public static string XmlSerializationException {
            get {
                return ResourceManager.GetString("XmlSerializationException", resourceCulture);
            }
        }
    }
}
